---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/{username}/reservations":
    parameters:
    - name: username
      in: path
      description: username
      required: true
      schema:
        type: string
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/api/v1/{username}/reservations/{id}":
    parameters:
    - name: username
      in: path
      description: username
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
